#!/bin/sh

set -eu

# github/strap related bootstrapping
if [ "$(uname -s)" = "Darwin" ]; then
  brew update >/dev/null
  brew bundle check &>/dev/null || brew bundle

  brew bootstrap-rbenv-ruby

  BUNDLE="brew bundle exec -- bundle"
else
  BUNDLE="bundle"
fi

$BUNDLE --path vendor/gems --local --binstubs
