#!/bin/sh
#!/bin/sh

set -eu

test -d "/usr/share/rbenv/shims" && {
  export PATH="/usr/share/rbenv/shims:$PATH"
  export RBENV_VERSION="2.3.1"
}

# -f to not error missing versions
rm -f Gemfile.lock Gemfile.rails5.lock

# clean out the ruby environment
export RUBYLIB=
export RUBYOPT=

script/bootstrap
script/test --format RspecJSONDumper::Formatter --format progress
