name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Set up Ruby 2.7.2
      uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
      with:
        ruby-version: 2.7.2
    - name: Build and test
      run: |
        bundle install --binstubs
        bin/rspec
